# 🟢 这是一个配置文件 (YAML格式)
# 就像填表格一样简单！

version: 1

# 1. 定义你的输出方式 (Handler)
handlers:
  # 控制台输出 (屏幕上看到的)
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  # 文件输出 (保存到文件)
  file:
    class: logging.FileHandler
    filename: "examples/logs/my_app.log"
    encoding: utf-8
    level: INFO
    formatter: json_fmt

# 2. 定义格式 (Formatter)
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 我们的框架自带了 JSON 格式，这里不需要定义复杂的 format 字符串
  json_fmt:
    (): log_framework.logger_setup.JSONFormatter

# 3. 组装起来 (Root Logger)
root:
  level: INFO
  handlers: [console, file]
